### ISSUE TITLE
server raises exception -- depending on django version

### ISSUE THREAD

**Issue by igemsoftwareadmin** [igemsoftware/HFUT-China_2015#3]
After successful installation with django 1.6, the server raises an error as soon as the first page is called.

python manage.py runserver 0.0.0.0:8000
Validating models...

0 errors found
September 22, 2015 - 15:26:38
Django version 1.6.1, using settings 'BioDesigner.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 67, in **call**
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in **call**
    self.load_middleware()
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 45, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/usr/lib/python2.7/dist-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class

**Comment by igemsoftwareadmin** [comment]
Actually, this error indicates that I am now using a too old Django version. Django 1.6 doesn't have this particular middleware module yet. You really have to tell developers which django version(s) are currently supported.
